export const GET_JOB_SUCCESS = 'GET_JOB_SUCCESS';
export const GET_JOB_LOADING = 'GET_JOB_LOADING';
export const GET_JOB_FAILED = 'GET_JOB_FAILED';

export const APPLY_JOB_SUCCESS = 'APPLY_JOB_SUCCESS';
export const APPLY_JOB_LOADING = 'APPLY_JOB_LOADING';
export const APPLY_JOB_FAILED = 'APPLY_JOB_FAILED';

